### ISSUE TITLE
what is the difference between 'provides' and 'results' ? 

### ISSUE THREAD

**Issue by tarun29061990** [danielduarte/flowed#34]
```
getDate: {
      provides: ['date'],
      resolver: {
        name: 'flowed::Echo',
        params: { in: { value: new Date() } },
        results: { out: 'date' },
      }
},
```
In the above configuration, what is the difference between provides and results ? Is it about task level and resolver level configuration?

**Comment by danielduarte** [comment]
`provides` are the values or "tokens" expected to be returned by a task in the flow.
They give a global name in the flow scope to the values that travel from task to task so any task that "requires" those values or tokens will be provided by any other task that "provides" it. Basically `provides` and `requires` fields form the edges in the flow graph.

And `results` is the instruction to map the desired results returned by a resolver into the values returned by the flow task to the rest of the flow. The left side of `results` have always the names returned by the resolver (no matter the flow where the resolver is being used, a resolver will always have the same possible values there since they are generated and returned internally in its code). And on the right side are a value/token name (one of the declared in `provides`) so the given resolver result is mapped to that value.

In your example using the resolver `flowed::Echo` (which always return a value called `out`) you're telling Flowed: "please name the 'out' result of this resolver as 'date' so any other task in the flow that requires 'date' will recibe that value.".

Hope my answer helps ;)
