### ISSUE TITLE
Can we support conditional branching?

### ISSUE THREAD

**Issue by tarun29061990** [danielduarte/flowed#35]
I have a use case where I need to support conditional branching or invoking a resolver based on some condition. For example:-

```
resolverA() {
    api_call.then(()=>{
        //business logic
    }).catch(()=>{
        //invoke resolverB 
    })
}
```

**Comment by danielduarte** [comment]
Flowed already support conditional branching by using the built-in resolver `flowed::Conditional`.

[Here](https://github.com/danielduarte/flowed/blob/main/doc/resolver-library.md#conditional) is the basic doc for branching. The important thing to use it is that you need to declare both possible tokens in your conditional task, for example `"provides": ["resultIfTrue", "resultIfFalse"]`, and the conditional resolver will return only one of them depending on the evaluation of the condition. Then if `resultIfTrue` is returned, only the task (branch) that requires `resultIfTrue` will be executed, or otherwise if `resultIfFalse` is returned then the "else" branch will be executed.

[Here](https://github.com/danielduarte/flowed/issues/31#issuecomment-718956326) is my answer in an older question about conditionals. Maybe it helps as well.

And finally if you need some help with a specific case and how to use conditionals there, just let me know and I'll try to help.
